name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-backend-prod:
    name: Deploy Backend to Production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend to Production
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend-prod:
    name: Deploy Frontend to Production
    runs-on: ubuntu-latest
    needs: deploy-backend-prod  # Wait for backend to deploy first
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Frontend to Production
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
